### ISSUE TITLE
Custom spoof build vars

### ISSUE THREAD

**Issue by osm0sis** [5ec1cff/TrickyStore#2]
This looks really impressive and promising! 

I see for spoof_build_vars you're still using sailfish print however, which will result in broken RCS (it passes integrity but is then somehow banned for RCS use).

Can you add the ability to provide our own build vars/print so people can also have working RCS with this module without needing to build it themselves?

**Comment by 5ec1cff** [comment]
pr is welcome

**Comment by chiteroman** [comment]
Will try to add support for it 👍

**Comment by 5ec1cff** [comment]
https://github.com/5ec1cff/TrickyStore/commit/4bbf952483389eef95dfe3612629560119b30fcc
