### ISSUE TITLE
[Help] Use with MicroG

### ISSUE THREAD

**Issue by Milor123** [5ec1cff/TrickyStore#3]
Guys, I would like know, that how should i use it with microG, it provide my Android ID and a Serial, but what should I put in the 
```
            <PrivateKey format="pem">
-----BEGIN EC PRIVATE KEY-----
...
-----END EC PRIVATE KEY-----
            </PrivateKey>
```

I am noob in it, i would like understand how fill it with easy steps. I want pass SafetyNet
Thank u very much guys

I am using CrDroid  A14 with Magisk (cannary version), have Zygisk Lsposed and Play Integraty Fix and Shamiko

Updated: I've tried use my AndroidID provided by MicroG and create the cert with
```
openssl ecparam -name prime256v1 -genkey -noout -out private-key.pem
openssl req -new -x509 -key private-key.pem -out certificate.pem -days 365
```

But **my phone stuck** in "Phone is starting..." after the unlock the phone.

**Comment by VisionR1** [comment]
Unfortunately, you need a valid keybox.xml
Before you ask.
Search on internet, or have friends and lot of luck.
