### ISSUE TITLE
strong not passed

### ISSUE THREAD

**Issue by TheArtyomMDev** [5ec1cff/TrickyStore#31]
i found an unrevoked keybox.xml and used it as said in instructions. I got bootloader locked verdict in key attestation, however play integrity and safety net still shows cts fail (basic passes) woth hardware backed method
Any thoughts?
My device is Redmi Note 10 Pro

**Comment by Myer921** [comment]
A potentially useful feedback is that on devices like the Pixel 6, using FPGO can pass through strong, but using TrickyStore does not work, regardless of whether spoof_build_vars + simulated TEE are used. On the OnePlus 9 (TEE error -10003), enabling TEE simulation does not have this issue.

Speculation? Different CTS passing standards for each device? Could spoof_build_vars be detected on specific models? Not particularly useful feedback. Of course, valid keyboxes, and I even have 6 valid keyboxes in my possession.

-----------

一个可能的有用的反馈，在 Pixel6 这种机器上，使用 FPGO 可以通过 strong ，但是用 TrickyStore 后不可以，无论是否 spoof_build_vars + 模拟 TEE ，均是这种情况。
在 Oneplus 9 (TEE error -10003) 中启用 TEE 模拟则没有这个问题。


猜测？每台机器的 CTS 通过标准不同？spoof_build_vars 在特定机型会被检测到？不是特别有用的反馈。
当然，有效的 keybox ，我的手里甚至还有 6 个有效 keybox 。

**Comment by Myer921** [comment]
After enabling spoof_build_vars, it even causes the basics to fail. This was tested on the Pixel 6.
在开启 spoof_build_vars 后甚至会导致 基础 都无法通过，这是在 Pixel6 中测试的。

**Comment by lokey0905** [comment]
在小米11 lite 5g (renoir)有相同的狀況
spoof_build_vars功能失效

**Comment by L1bws** [comment]
在Pixel 4XL(Coral)上也有相同情况
spoof_build_vars功能失效
PI只能通过Basic

**Comment by TheArtyomMDev** [comment]
> Speculation? Different CTS passing standards for each device? Could spoof_build_vars be detected on specific models? Not particularly useful feedback. Of course, valid keyboxes, and I even have 6 valid keyboxes in my possession. 

So with OnePlus did u get strong integrity working?
did u use spoof build vars or not?

**Comment by Myer921** [comment]
> > Speculation? Different CTS passing standards for each device? Could spoof_build_vars be detected on specific models? Not particularly useful feedback. Of course, valid keyboxes, and I even have 6 valid keyboxes in my possession.
> 
> So with OnePlus did u get strong integrity working? did u use spoof build vars or not?

Using Apatch+Shamiko+ZygiskNext+TrickyStore on the OnePlus 9 passes without enabling spoof_build_vars.

**Comment by TheArtyomMDev** [comment]
> Using Apatch+Shamiko+ZygiskNext+TrickyStore on the OnePlus 9 passes without enabling spoof_build_vars.

So u not using tricky store and using apatch instead, right?

**Comment by Myer921** [comment]
> > Using Apatch+Shamiko+ZygiskNext+TrickyStore on the OnePlus 9 passes without enabling spoof_build_vars.在 OnePlus 9 上使用 Apatch+Shamiko+ZygiskNext+TrickyStore 可以通过，无需启用 spoof_build_vars。
> 
> So u not using tricky store and using apatch instead, right?所以你不使用棘手的商店而是使用补丁，对吗？

I use Apatch because I can't use kernelsu; my phone's kernel is not within the supported range of kernelsu.
The TrickyStore module I use can pass STRONG without enabling spoof_build_vars.

**Comment by Myer921** [comment]
For Pixel devices, please use Pixel sailfish device information. Using FPGO can pass STRONG, and it can also pass strong without using Pixel sailfish. However, after installing LSPosed, it will not maintain STRONG.

**Comment by pndwal** [comment]
For those not using Shamiko, this or a similar means to spoof sensitive props (globally) will be needed (since we no longer have MagiskHide doing it)...

**Comment by TheArtyomMDev** [comment]
> I use Apatch because I can't use kernelsu
Which shamiko version are u using with apatch?

**Comment by TheArtyomMDev** [comment]
sadly using even Apatch+Shamiko+ZygiskNext+TrickyStore didnt work for me, still cts failed

**Comment by Myer921** [comment]
> > I use Apatch because I can't use kernelsu
> 
> Which shamiko version are u using with apatch?

Shamiko-v0.7.4-188-release

Apatch can only use this version. If your kernel is greater than 5.10, please use kernelsu, so you don't have to worry about using the older version of Shamiko.

**Comment by Myer921** [comment]
https://t.me/real5ec1cff_discuss/14861
^ An interesting phenomenon is that this type of TEE error is not because TEE is hidden, but because GMS detected something and directly refused to work. (Usually, uninstalling all modules and leaving it for a while will resolve itself.)

^^ Personal speculation: because last time the PIF module SW KEYBOX strong turned from valid to invalid, I used PIF 16.3 for a long time. Then one day, when I wanted to continue testing the new keybox, my TEE had this kind of error. (Of course, uninstalling the modules and leaving it for a while resolved itself.)


^ 一个有趣现象，这种类型的 TEE 报错不是因为 TEE 隐藏了，而是 GMS 检测到了什么直接拒绝工作了。(通常卸载掉所有模块后放置一段时间会自己恢复)
^^ 个人猜测，因为上次 PIF 模块 SW KEYBOX strong 有效到无效，我使用了很长一段时间的 PIF 16.3 ，然后有一天想继续测试 new keybox 时我的 TEE 就是这样的错误。（当然。卸载掉模块放置一阵子自己恢复了）

**Comment by pndwal** [comment]
@Myer921

Have you been using latest 1.0.3 or CI (actions) builds before that?... I think some issues you mention are gone with recent merges, eg spoof_build_vars can work, especially with additional (new) prop spoofing, and the (later) sailfish print included _does_ actually allow RCS. 😉

**Comment by skcpt6230** [comment]
> For Pixel devices, please use Pixel sailfish device information. Using [FPGO](https://github.com/changhuapeng/FrameworkPatcherGO) can pass STRONG, and it can also pass strong without using Pixel sailfish. However, after installing LSPosed, it will not maintain STRONG. ^ The above tests were conducted on the Pixel 6 and Pixel 4.
> 
> OnePlus users theoretically do not need to add ! in the application list as long as there is no TEE error -10003. ^ The above tests were conducted on the OnePlus 9 and OnePlus 10T.

Pixel sailfish information still not works, cannot pass BASIC, tested on Pixel 6

**Comment by Myer921** [comment]
> @Myer921
> 
> Have you been using latest 1.0.3 or CI (actions) builds before that?... I think some issues you mention are gone with recent merges, eg spoof_build_vars can work, especially with additional (new) prop spoofing, and the (later) sailfish print included _does_ actually allow RCS. 😉

The current GitHub code version (6f82e40) has different device variables verified for each machine, which is related to each model's CTS certification (this is speculation). However, I cannot test RCS because Google SMS does not support its use in my region at all.

**Comment by Myer921** [comment]
> > For Pixel devices, please use Pixel sailfish device information. Using [FPGO](https://github.com/changhuapeng/FrameworkPatcherGO) can pass STRONG, and it can also pass strong without using Pixel sailfish. However, after installing LSPosed, it will not maintain STRONG. ^ The above tests were conducted on the Pixel 6 and Pixel 4.
> > OnePlus users theoretically do not need to add ! in the application list as long as there is no TEE error -10003. ^ The above tests were conducted on the OnePlus 9 and OnePlus 10T.
> 
> Pixel sailfish information still not works, cannot pass BASIC, tested on Pixel 6

Please try using the following combination, or replace Apatch with kernelsu (if your kernel is greater than 5.10):
Apatch+Shamiko+ZygiskNext+FPGO

Tip: My Pixel 6 has the same issue as yours; using TrickyStore + spoof_build_vars cannot pass strong.
