### ISSUE TITLE
Icon

### ISSUE THREAD

**Issue by VisionR1** [5ec1cff/TrickyStore#45]
If you decide make a app and want icon or just for the module, I have some ideas.
![TrickyStore](https://github.com/user-attachments/assets/d6519d04-ec0f-4347-8b6d-b8085c5b85b3)
![TrickyStore1](https://github.com/user-attachments/assets/da97c50d-300f-4385-aa8f-9e3446f8af50)

**Comment by osm0sis** [comment]
Probably you should close this since there's no need for an icon...

**Comment by selfmusing** [comment]
bruh 💀

**Comment by VisionR1** [comment]
> Probably you should close this since there's no need for an icon...

True. 
I had forget is still open.😂🤣
