### ISSUE TITLE
All Apps Target

### ISSUE THREAD

**Issue by tryigit** [5ec1cff/TrickyStore#48]
target.txt

Why not add a shortcut to the app to apply the target (spoof) to all apps? Some might prefer that.

Like:
`allapps!`

In customize.sh we can also add a +/- function to select but I don't like it because it's unprofessional.

Also the blacklist feature makes sense.
(https://github.com/5ec1cff/TrickyStore/issues/48#issuecomment-2295838955)

**Comment by joeyoropesa-dev** [comment]
I would personally prefer this feature to select all apps and all future apps to be applied globally (so that this module will affect every single app installed and instead of making whitelist (target) for us, we could have blacklist.txt that will have list of packages that will not be spoofed)

**Comment by joeyoropesa-dev** [comment]
I've tried to add code as an example for this kind of changes in #51 but for some reasons I have some bad feelings that dev probably will not agree for this feature to be implemented. It's like that the dev required in purpose target.txt to have specific packages and not letting all packages be spoofed for some reason..

Anyway, let's hope for our best - pull request has been created.

**Comment by joeyoropesa-dev** [comment]
@5ec1cff Don't be coward but answer why you don't want this feature to be at least optional to your module


Is this a reason why you changed to **CLOSED SOURCE**
