### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by Gunkkk** [5ec1cff/TrickyStore#5]
Why the PK of CSR in hackleaf is still the PK in keybox instead of the real generated public key please  ?
Also, why not just hook the store_new_key or generatekey before persisent, since the chains will be saved in db once generated, is there any considerations please?

**Comment by aviraxp** [comment]
What is pk and csr?

**Comment by Gunkkk** [comment]
> What is pk and csr?

public key and cert signing request ,which is the args of X509v3CertificateBuilder

**Comment by 5ec1cff** [comment]
You can submit a PR

**Comment by osm0sis** [comment]
> > Why the PK of CSR in hackleaf is still the PK in keybox instead of the real generated public key please ?
> 
> [d4cf6a3](https://github.com/5ec1cff/TrickyStore/commit/d4cf6a3450ef5b955663f07b8901be1bc9f849cf)

Seems to throw a "Not trusted" red warning banner in Key Attestation Demo, though otherwise still passes STRONG.

**Comment by Gunkkk** [comment]
> > > Why the PK of CSR in hackleaf is still the PK in keybox instead of the real generated public key please ?
> > 
> > 
> > [d4cf6a3](https://github.com/5ec1cff/TrickyStore/commit/d4cf6a3450ef5b955663f07b8901be1bc9f849cf)
> 
> Seems to throw a "Not trusted" red warning banner in Key Attestation Demo, though otherwise still passes STRONG. Reverted to 1.0.2-57 and all is good again.
> 
> That's with custom spoof_build_vars and the following target.txt:
> 
> ```
> com.google.android.gms
> io.github.vvb2060.keyattestation
> io.github.vvb2060.mahoshojo
> icu.nullptr.nativetest
> com.reveny.nativecheck
> io.github.huskydg.memorydetector
> ```

@osm0sis I think u enable the 'use app attest' feature and that cannot hardly be mocked since the 4th cert is signed by keys in keystore. Certainly, the previous version that always gives the same keypair  will not fail in the certs chain verification  but it does not work reasonablely I think.
