### ISSUE TITLE
Install fail. Unsupported platform: arm

### ISSUE THREAD

**Issue by segor77** [5ec1cff/TrickyStore#56]
When I try to install the module (v1.1.1), I get an error "Unsupported platform: arm". 
v1.0.4 install ok.

Can this be fixed?

(Samsung Galaxy A01 Android 12 Stock ROM )

Thanx))

**Comment by 5ec1cff** [comment]
v1.0.4 does not exist

**Comment by osm0sis** [comment]
1.0.4 is chiteroman's fork. 😄

There were a few different forks that tried to add arm support. Not sure if it works there, or if not, what other barriers exist to it being functional.

**Comment by osm0sis** [comment]
@5ec1cff, apparently it was tested and works!

See: https://github.com/chiteroman/TrickyStore/pull/9

**Comment by 5ec1cff** [comment]
Added in [1.1.2](https://github.com/5ec1cff/TrickyStore/releases/tag/1.1.2)
