### ISSUE TITLE
Version 1.1.2(123) Installation Fails

### ISSUE THREAD

**Issue by mrksbk** [5ec1cff/TrickyStore#57]
The installation fails on Pixel 7 with Android 15 beta.

Edit:
Direkt download from Github an install it manually and not through magisk update function solved the issue in my case.

**Comment by mrksbk** [comment]
Solved.
Direkt download from Github an install it manually and not through magisk update function solved the issue.

**Comment by molitar** [comment]
Did not fix it for me I have a Pixel Fold.  It will not install I'm stuck with v1.1.1

**Comment by 5ec1cff** [comment]
Please provide a screenshot of the failed installation

**Comment by mrksbk** [comment]
In my case it happens when I try to install the downloaded version of Magisk.
![Screenshot_20240823-104925](https://github.com/user-attachments/assets/de9a1b1d-d3d2-4548-97ab-06c7d8076c33)

**Comment by d3rt0xx** [comment]
Same problem here. Downloaded zip and tried to install thru Magisk

Google Pixel 7
Stock Android 14

**Comment by 5ec1cff** [comment]
Please send logcat.
You can run `adb logcat > log.txt` and then reproduce this installation failure

**Comment by d3rt0xx** [comment]
> Please send logcat. You can run `adb logcat > log.txt` and then reproduce this installation failure

[log.txt](https://github.com/user-attachments/files/16726498/log.txt)

Think its the new AARCH-logic in customize.sh, but im just a noob

**Comment by molitar** [comment]
Hello here is my log.txt 
[log.txt](https://github.com/user-attachments/files/16727540/log.txt)

**Comment by KAPABLE-K** [comment]
I had this problem I had to delete and redownload the file and it worked.

**Comment by 5ec1cff** [comment]
The issue has been confirmed and will be fixed in the next version

**Comment by osm0sis** [comment]
Fully uninstalling 1.1.1 (i.e. rebooted in between) then installing 1.1.2 got it working for me in the meantime. 👍

**Comment by sawdoctor** [comment]
> Did not fix it for me I have a Pixel Fold.  It will not install I'm stuck with v1.1.1

Know it probably doesn't help, I'm running a pixel fold latest magisk canary. I used the upside from magisk to download the update then manually flashed it and everything went ok

**Comment by molitar** [comment]
> The issue has been confirmed and will be fixed in the next version

So any rough estimate for fix so can install?

**Comment by molitar** [comment]
OK I got Tricky Store 1.1.2 to install following these steps.

1. Uninstall 1.1.1 and reboot
2. Delete the tricky_store folder /data/adb/tricky_store/
3. Flash the new 1.1.2

**Comment by osm0sis** [comment]
@5ec1cff "Failed to prepare environment" is confirmed fixed with 1.1.3 (updated from 1.1.2), but after the reboot TS disabled itself again. Magisk 27007.

**Comment by molitar** [comment]
The new 1.1.4 release installed perfectly fine and still passing strong so no issue with new release.

**Comment by osm0sis** [comment]
The real test will be when it rolls out on the module auto-update.

Edit: Wait.. 1.1.4 from where? I don't see it posted anywhere; not here or on TG.
