### ISSUE TITLE
Shamiko show unsupported environment with TrickStore v1.1.2

### ISSUE THREAD

**Issue by mspw11** [5ec1cff/TrickyStore#58]
Shamiko works well with trickstore v1.1.1
But it stops working when I update ts to v1.1.2

- device: oneplus ace 3
- os : coloros 14
- root: ksu-lkm (v1.0.1 11928)
- zygisk next : v1.1.0-330
- shamiko : v1.1.1 (357)
[KernelSU_bugreport_2024-08-24_13_57.tar.gz](https://github.com/user-attachments/files/16735546/KernelSU_bugreport_2024-08-24_13_57.tar.gz)

**Comment by 5ec1cff** [comment]
try reinstall the module

**Comment by mspw11** [comment]
After uninstalling and reinstalling ts, shamiko worked again.
Maybe it's caused by updating the module directly from ksu manager
