### ISSUE TITLE
Cannot work with shamiko357

### ISSUE THREAD

**Issue by AMWss** [5ec1cff/TrickyStore#59]
When this module installed, shamiko 357 report ''unsupported environment''.
Redmi K50 Ultra
Android 14
5.10.210
zygisk_next 1.1.0
ksu 1.0.1 with the latest lkm mode

**Comment by mspw11** [comment]
https://github.com/5ec1cff/TrickyStore/issues/58
Have a try

**Comment by MhmRdd** [comment]
I had similar issue, either you install latest ZygiskNext & Shamiko, or uninstall shamiko & reboot, then install shamiko & reboot again.
It should work.
