### ISSUE TITLE
Incorrect default mode on OnePlus devices

### ISSUE THREAD

**Issue by osm0sis** [5ec1cff/TrickyStore#60]
On my OnePlus 5 using TS 1.1.3 shows tee_status teeBroken=false, and with either the automatic default or target.txt entries forced with ? the output in Key Attestation Demo (KAD) is Keymaster 3.0 Software and it fails STRONG, but with target.txt entries forced with ! the output in KAD is KeyMint 1.0 TrustedEnvironment and STRONG can be achieved. 

I believe this means TS's automatic default chose incorrectly? Happy to test or log whatever you like to help fix it. 🙂

**Comment by aviraxp** [comment]
https://developer.android.com/privacy-and-security/security-key-attestation

It is not chosen incorrectly, it is just Google doesn't like software keymaster (which means the device does not have TEE). I am not sure if TS should be switched to generating keypair mode in this case.

**Comment by osm0sis** [comment]
Ah, but isn't that only because the OnePlus bootloader is unlocked? Doesn't that amount to its TEE being broken?

**Comment by aviraxp** [comment]
No, it's either device doesn't have TEE hardware, or TEE hardware doesn't support userspace key encryption at all (I expect this on old devices). So the device ship with a software-implemented keymaster hal.

**Comment by osm0sis** [comment]
Thanks for trying to explain. I guess the confusing part is people always refer to OnePlus' TEE as broken, but you're saying that's just a misnomer?

**Comment by aviraxp** [comment]
TEE broken is a incorrect presentation from the beginning, it is jusy becuase of momo using wrong words. Userspace only knows that a keypair cannot be generated from TEE (maybe started fron oneplus7)?, it doesn't mean the hardware is broken.

**Comment by aviraxp** [comment]
This is workarounded internally by check if cert generated is hardware-backed.

**Comment by pndwal** [comment]
Y̶e̶a̶h̶, O̶P̶5̶ i̶s̶ u̶n̶u̶s̶u̶a̶l̶ i̶n̶ t̶h̶a̶t̶ l̶a̶u̶n̶c̶h̶e̶d̶ w̶i̶t̶h̶ K̶e̶y̶m̶a̶s̶t̶e̶r̶ 3̶ H̶A̶L̶ a̶n̶d̶ A̶7̶.... Google says devices should have A8+ for that... [Edit: It now seems to me that OP5 likely did launch with Keymaster 2 or lower, but somehow received an update to the HAL/Keymaster later. More edits in [ ] below.] As such (despite having key attestation from Keymaster 2),  A7 LV devices shouldn't produce proper attestation to keypairs originating from secure hardware for play Integrity purposes anyway...

It seems that the A8+ LV prerequisite for this should simply be ensured both by the Keymaster 3 requirement and TrustedEnvironment (or better) in the Google model... In OP5 [with updated Keymaster], it's the SecurityLevel showing as Software that [still] properly marks the device as non-compliant (below spec). [Apparently Software SecurityLevel is expected from sub-A8 LV devices even with updated Keymaster... Hacking attestation data to show TrustedEnvironment or Strongbox can allow STRONG verdict, at least with Android updated to A8+]

> This is workarounded internally by check if cert generated is hardware-backed.

So seems this check is still good as it assumes accurate OEM attestation values, and I guess that even if a device has capable Keymaster and TEE storage for keypairs, it's likely that Android 7 simply wouldn't support a S/N or PI hardware backed attestation implementation properly. However, with Android 8+ installed, users can easily bypass your test with ! in target.txt (bumps/spoofs SecurityLevel to TrustedEnvironment).

**Comment by osm0sis** [comment]
> This is workarounded internally by check if cert generated is hardware-backed.

@aviraxp On 1.2.0-RC1 with my OP5 and it still needed ! added to manually force it, so unless your fix is further upstream from RC1 unfortunately this issue doesn't seem fixed yet.

**Comment by aviraxp** [comment]
logs？

**Comment by osm0sis** [comment]
Here you go!
[logcat-auto.txt](https://github.com/user-attachments/files/16987063/logcat-auto.txt)
[logcat-forced.txt](https://github.com/user-attachments/files/16987064/logcat-forced.txt)

I just grepped for Tricky. Let me know if/what you need more and I'll upload. 👍

**Comment by aviraxp** [comment]
Can you show your key attestation result when no ！ ？

**Comment by osm0sis** [comment]
Will upload a pic after work today, but it showed locked with the keybox, but still showed Software Keymaster 3.0 HAL.

Edit: @aviraxp
![Screenshot_20240913-163541_Key Attestation](https://github.com/user-attachments/assets/b032a569-1696-41a2-bdcb-e8843ecbc95d)

**Comment by aviraxp** [comment]
[Tricky-Store-v1.1.3-147-c7b01e5-release.zip](https://github.com/user-attachments/files/17005927/Tricky-Store-v1.1.3-147-c7b01e5-release.zip)
Try this

**Comment by pndwal** [comment]
FWIW, it now seems to me that these older devices most likely got Keymaster 3 HAL and higher (a Motorola device launched with A6 had 4.1) probably launched with 2.0 or earlier but the HAL later received update(s). Security level remained as expected for pre A8 devices, however ie set to Software.

**Comment by osm0sis** [comment]
Similar, but different. No NPE anymore at least!

auto:
```
09-15 14:11:22.622  1662  1699 I TrickyStore: hack key for u10141 unstable.c7202ece89390c490b1b94d5b71225e1.2226553170591784700
09-15 14:11:22.622  1662  1699 E TrickyStore: failed to get verified boot key or hash from original, use randomly generated instead
09-15 14:11:22.622  1662  1699 E TrickyStore: java.security.cert.CertificateParsingException: Expected sequence for root of trust, found i4
09-15 14:11:22.622  1662  1699 E TrickyStore: 	at Xf.a(Unknown Source:1069)
09-15 14:11:22.622  1662  1699 E TrickyStore: 	at w1.onTransact(Unknown Source:138)
09-15 14:11:22.622  1662  1699 E TrickyStore: 	at android.os.Binder.execTransactInternal(Binder.java:1505)
09-15 14:11:22.622  1662  1699 E TrickyStore: 	at android.os.Binder.execTransact(Binder.java:1444)
09-15 14:11:22.626  1662  1699 I TrickyStore: return hacked cert of uid=10141 a=unstable.c7202ece89390c490b1b94d5b71225e1.2226553170591784700
09-15 14:11:22.634  1662  1699 I TrickyStore: remove key for u10141 unstable.c7202ece89390c490b1b94d5b71225e1.2226553170591784700 because service.deleteKey
09-15 14:11:30.136  4170  9030 I okhttp.OkHttpClient: --> GET https://5ec1cff.github.io/TrickyStore/update.json
09-15 14:11:30.146  4170  9030 I okhttp.OkHttpClient: <-- 200 https://5ec1cff.github.io/TrickyStore/update.json (10ms, 251-byte body)
09-15 14:11:36.879  1662  1699 I TrickyStore: hack key for u10205 KeyAttestation
09-15 14:11:36.880  1662  1699 E TrickyStore: failed to get verified boot key or hash from original, use randomly generated instead
09-15 14:11:36.880  1662  1699 E TrickyStore: java.security.cert.CertificateParsingException: Expected sequence for root of trust, found i4
09-15 14:11:36.880  1662  1699 E TrickyStore: 	at Xf.a(Unknown Source:1069)
09-15 14:11:36.880  1662  1699 E TrickyStore: 	at w1.onTransact(Unknown Source:138)
09-15 14:11:36.880  1662  1699 E TrickyStore: 	at android.os.Binder.execTransactInternal(Binder.java:1505)
09-15 14:11:36.880  1662  1699 E TrickyStore: 	at android.os.Binder.execTransact(Binder.java:1444)
09-15 14:11:36.889  1662  1699 I TrickyStore: return hacked cert of uid=10205 a=KeyAttestation
09-15 14:11:47.571  1662  1699 I TrickyStore: hack key for u10141 unstable.c7202ece89390c490b1b94d5b71225e1.-5390576515882497312
09-15 14:11:47.572  1662  1699 E TrickyStore: failed to get verified boot key or hash from original, use randomly generated instead
09-15 14:11:47.572  1662  1699 E TrickyStore: java.security.cert.CertificateParsingException: Expected sequence for root of trust, found i4
09-15 14:11:47.572  1662  1699 E TrickyStore: 	at Xf.a(Unknown Source:1069)
09-15 14:11:47.572  1662  1699 E TrickyStore: 	at w1.onTransact(Unknown Source:138)
09-15 14:11:47.572  1662  1699 E TrickyStore: 	at android.os.Binder.execTransactInternal(Binder.java:1505)
09-15 14:11:47.572  1662  1699 E TrickyStore: 	at android.os.Binder.execTransact(Binder.java:1444)
09-15 14:11:47.577  1662  1699 I TrickyStore: return hacked cert of uid=10141 a=unstable.c7202ece89390c490b1b94d5b71225e1.-5390576515882497312
09-15 14:11:47.584  1662  1699 I TrickyStore: remove key for u10141 unstable.c7202ece89390c490b1b94d5b71225e1.-5390576515882497312 because service.deleteKey
09-15 14:11:52.069  1662  1699 I TrickyStore: hack key for u10141 unstable.c7202ece89390c490b1b94d5b71225e1.4312576736081739191
09-15 14:11:52.070  1662  1699 E TrickyStore: failed to get verified boot key or hash from original, use randomly generated instead
09-15 14:11:52.070  1662  1699 E TrickyStore: java.security.cert.CertificateParsingException: Expected sequence for root of trust, found i4
09-15 14:11:52.070  1662  1699 E TrickyStore: 	at Xf.a(Unknown Source:1069)
09-15 14:11:52.070  1662  1699 E TrickyStore: 	at w1.onTransact(Unknown Source:138)
09-15 14:11:52.070  1662  1699 E TrickyStore: 	at android.os.Binder.execTransactInternal(Binder.java:1505)
09-15 14:11:52.070  1662  1699 E TrickyStore: 	at android.os.Binder.execTransact(Binder.java:1444)
09-15 14:11:52.074  1662  1699 I TrickyStore: return hacked cert of uid=10141 a=unstable.c7202ece89390c490b1b94d5b71225e1.4312576736081739191
09-15 14:11:52.088  1662  1699 I TrickyStore: remove key for u10141 unstable.c7202ece89390c490b1b94d5b71225e1.4312576736081739191 because service.deleteKey
```

![Screenshot_20240915-141703_Key Attestation](https://github.com/user-attachments/assets/b6b520c1-6e49-4d80-ae8c-7e6bd8119c41)

Still Software Keymaster 3.0 instead of the KeyMint 1.0 that forcing with ! gets.

**Comment by aviraxp** [comment]
[Tricky-Store-v1.1.3-147-a9e5a9e-release.zip](https://github.com/user-attachments/files/17008983/Tricky-Store-v1.1.3-147-a9e5a9e-release.zip)
[Tricky-Store-v1.1.3-146-4acaa6c-release.zip](https://github.com/user-attachments/files/17008984/Tricky-Store-v1.1.3-146-4acaa6c-release.zip)

Try these 2

**Comment by osm0sis** [comment]
No errors anymore, so nice job there, but unfortunately still no Strong without forcing it using ! which shows KeyMint 1.0.

147 auto:
```
09-16 19:05:05.417  1604  1679 I TrickyStore: hack key for u10141 unstable.c7202ece89390c490b1b94d5b71225e1.-1577129055186367130
09-16 19:05:05.476  1604  1679 I TrickyStore: return hacked cert of uid=10141 a=unstable.c7202ece89390c490b1b94d5b71225e1.-1577129055186367130
09-16 19:05:05.488  1604  1679 I TrickyStore: remove key for u10141 unstable.c7202ece89390c490b1b94d5b71225e1.-1577129055186367130 because service.deleteKey
09-16 19:05:13.334  5336  9007 I okhttp.OkHttpClient: --> GET https://5ec1cff.github.io/TrickyStore/update.json
09-16 19:05:13.342  5336  9007 I okhttp.OkHttpClient: <-- 200 https://5ec1cff.github.io/TrickyStore/update.json (7ms, 251-byte body)
09-16 19:05:20.847  1604  1679 I TrickyStore: hack key for u10205 KeyAttestation
09-16 19:05:20.855  1604  1679 I TrickyStore: return hacked cert of uid=10205 a=KeyAttestation
09-16 19:06:13.674  1604  1679 I TrickyStore: hack key for u10141 unstable.c7202ece89390c490b1b94d5b71225e1.8309253262807812808
09-16 19:06:13.678  1604  1679 I TrickyStore: return hacked cert of uid=10141 a=unstable.c7202ece89390c490b1b94d5b71225e1.8309253262807812808
09-16 19:06:13.686  1604  1679 I TrickyStore: remove key for u10141 unstable.c7202ece89390c490b1b94d5b71225e1.8309253262807812808 because service.deleteKey
09-16 19:06:52.057  5336  9399 I okhttp.OkHttpClient: --> GET https://5ec1cff.github.io/TrickyStore/update.json
09-16 19:06:52.062  5336  9399 I okhttp.OkHttpClient: <-- 200 https://5ec1cff.github.io/TrickyStore/update.json (4ms, 251-byte body)
```
![147](https://github.com/user-attachments/assets/bcd4e04a-07c2-435b-885f-23910f179fd9)

146 auto:
```
09-16 19:09:28.607  1630  1686 I TrickyStore: return hacked cert of uid=10205 a=KeyAttestation
09-16 19:09:43.292  1630  1691 I TrickyStore: hack key for u10141 unstable.c7202ece89390c490b1b94d5b71225e1.fallback
09-16 19:09:43.301  1630  1691 I TrickyStore: return hacked cert of uid=10141 a=unstable.c7202ece89390c490b1b94d5b71225e1.fallback
09-16 19:09:45.075  1630  1691 I TrickyStore: hack key for u10141 unstable.c7202ece89390c490b1b94d5b71225e1.fallback
09-16 19:09:45.086  1630  1691 I TrickyStore: return hacked cert of uid=10141 a=unstable.c7202ece89390c490b1b94d5b71225e1.fallback
09-16 19:09:48.193  1630  1691 I TrickyStore: return hacked cert of uid=10141 a=unstable.c7202ece89390c490b1b94d5b71225e1.fallback
09-16 19:09:48.198  1630  1691 I TrickyStore: return hacked cert of uid=10141 a=unstable.c7202ece89390c490b1b94d5b71225e1.fallback
09-16 19:09:48.239  1630  1691 I TrickyStore: hack key for u10141 unstable.c7202ece89390c490b1b94d5b71225e1.5522267215767835852
09-16 19:09:48.248  1630  1691 I TrickyStore: hack key for u10141 unstable.c7202ece89390c490b1b94d5b71225e1.-6627318925871954883
09-16 19:09:48.252  1630  1686 I TrickyStore: return hacked cert of uid=10141 a=unstable.c7202ece89390c490b1b94d5b71225e1.5522267215767835852
09-16 19:09:48.253  1630  1686 I TrickyStore: return hacked cert of uid=10141 a=unstable.c7202ece89390c490b1b94d5b71225e1.-6627318925871954883
09-16 19:09:48.259  1630  1686 I TrickyStore: remove key for u10141 unstable.c7202ece89390c490b1b94d5b71225e1.5522267215767835852 because service.deleteKey
09-16 19:09:48.267  1630  1686 I TrickyStore: remove key for u10141 unstable.c7202ece89390c490b1b94d5b71225e1.-6627318925871954883 because service.deleteKey
09-16 19:09:52.336  1630  1686 I TrickyStore: return hacked cert of uid=10141 a=unstable.c7202ece89390c490b1b94d5b71225e1.fallback
09-16 19:09:52.382  1630  1686 I TrickyStore: hack key for u10141 unstable.c7202ece89390c490b1b94d5b71225e1.-5100845096549326595
09-16 19:09:52.390  1630  1686 I TrickyStore: return hacked cert of uid=10141 a=unstable.c7202ece89390c490b1b94d5b71225e1.-5100845096549326595
09-16 19:09:52.412  1630  1686 I TrickyStore: remove key for u10141 unstable.c7202ece89390c490b1b94d5b71225e1.-5100845096549326595 because service.deleteKey
```
![146](https://github.com/user-attachments/assets/67901e51-3945-4ad1-a706-29ec84ce517d)

**Comment by aviraxp** [comment]
OK, lets's sum up. The issue is OnePlus 5 is too old (launched before Oreo), although it has a TEE and can be used for encryption and keystore, it does not support do attestation in TEE. (So the attestation security level and keymaster security level are all software, rootOfTrust is SW as well). **In theory this device should not get strong even if bootloader is locked.**

In hack cert mode, only rootOfTrust filed is modified. I think current code does nothing wrong. The issue is GMS doesn't like it (maybe due to the reason I wrote in first paragraph). If we need to pass it in hack mode, i think we need to modify securityLevel filed to mock TEE enforced and move rootOfTrust to TEE enforced. As this is trick for keystore not play integrity, I don't want to touch it.

Another workaround is to parse the cert and auto switch to generating keypair mode if attestation level is software. But I am not sure if this wants to be the default behavior.

**Comment by pndwal** [comment]
> OK, lets's sum up. The issue is OnePlus 5 is too old (launched before Oreo), although it has a TEE and can be used for encryption and keystore, it does not support do attestation in TEE.

Yeah, but my understanding is that Keymaster 3 HAL _does_ support both the hardware key based attestation and ID attestation needed... However it now seems likely that this device was launched with only Keymaster 2 (below spec despite HKA support) but received an _update to 3 later_... As I wrote (and removed since marked off topic), another device (Motorola) launched with A6 had Keymaster 4.1!

I've edited my post above to reflect this, but I do agree that devices launched with A7 etc probably retain Software security level for a reason despite updated attestation capability... There may be unrelated reasons for updating HAL/Keymaster too.

> (So the attestation security level and keymaster security level are all software, rootOfTrust is SW as well). **In theory this device should not get strong even if bootloader is locked.**

Could updated HAL/Keymaster explain that?

> In hack cert mode, only rootOfTrust filed is modified. I think current code does nothing wrong. The issue is GMS doesn't like it (maybe due to the reason I wrote in first paragraph). If we need to pass it in hack mode, i think we need to modify securityLevel filed to mock TEE enforced and move rootOfTrust to TEE enforced. As this is trick for keystore not play integrity, I don't want to touch it.

👍

**Comment by ghost** [comment]
@aviraxp

Try with this:

```java
encodables[1] = new ASN1Enumerated(1);
encodables[3] = new ASN1Enumerated(1);
```

Should enforce Security Level to TEE.

(Not tested)

**Comment by aviraxp** [comment]
[Tricky-Store-v1.2.0-RC1-148-1d482fa-release-1.zip](https://github.com/user-attachments/files/17089566/Tricky-Store-v1.2.0-RC1-148-1d482fa-release-1.zip)
[Tricky-Store-v1.2.0-RC1-148-1d482fa-release-2.zip](https://github.com/user-attachments/files/17089567/Tricky-Store-v1.2.0-RC1-148-1d482fa-release-2.zip)
try these 2

**Comment by osm0sis** [comment]
Nice work!!

release-1:
```
09-22 15:30:07.210  1656  1705 I TrickyStore: hack key for u10141 unstable.c7202ece89390c490b1b94d5b71225e1.-5082968268987079497
09-22 15:30:07.271  1656  1705 I TrickyStore: hack key for u10141 unstable.c7202ece89390c490b1b94d5b71225e1.8727535832478331160
09-22 15:30:07.272  1656  1715 I TrickyStore: return hacked cert of uid=10141 a=unstable.c7202ece89390c490b1b94d5b71225e1.-5082968268987079497
09-22 15:30:07.291  1656  1705 I TrickyStore: remove key for u10141 unstable.c7202ece89390c490b1b94d5b71225e1.-5082968268987079497 because service.deleteKey
09-22 15:30:07.300  1656  1705 I TrickyStore: return hacked cert of uid=10141 a=unstable.c7202ece89390c490b1b94d5b71225e1.8727535832478331160
09-22 15:30:07.347  1656  1705 I TrickyStore: remove key for u10141 unstable.c7202ece89390c490b1b94d5b71225e1.8727535832478331160 because service.deleteKey
09-22 15:30:11.530  1656  1705 I TrickyStore: key u10141 unstable.c7202ece89390c490b1b94d5b71225e1.fallback not in our keystore, try re-gen!
09-22 15:30:11.583  1656  1705 I TrickyStore: hack key for u10141 unstable.c7202ece89390c490b1b94d5b71225e1.-1590453625440527732
09-22 15:30:11.588  1656  1705 I TrickyStore: return hacked cert of uid=10141 a=unstable.c7202ece89390c490b1b94d5b71225e1.-1590453625440527732
09-22 15:30:11.617  1656  1705 I TrickyStore: remove key for u10141 unstable.c7202ece89390c490b1b94d5b71225e1.-1590453625440527732 because service.deleteKey
09-22 15:30:12.310  1656  1705 I TrickyStore: key u10141 unstable.c7202ece89390c490b1b94d5b71225e1.fallback not in our keystore, try re-gen!
09-22 15:30:12.423  1656  1705 I TrickyStore: hack key for u10141 unstable.c7202ece89390c490b1b94d5b71225e1.5926250680578625349
09-22 15:30:12.429  1656  1705 I TrickyStore: return hacked cert of uid=10141 a=unstable.c7202ece89390c490b1b94d5b71225e1.5926250680578625349
09-22 15:30:12.467  1656  1705 I TrickyStore: remove key for u10141 unstable.c7202ece89390c490b1b94d5b71225e1.5926250680578625349 because service.deleteKey
09-22 15:30:16.381  1656  1705 I TrickyStore: hack key for u10205 KeyAttestation
09-22 15:30:16.396  1656  1705 I TrickyStore: return hacked cert of uid=10205 a=KeyAttestation
09-22 15:30:19.116  1656  1705 I TrickyStore: hack key for u10205 KeyAttestation
09-22 15:30:19.122  1656  1705 I TrickyStore: return hacked cert of uid=10205 a=KeyAttestation
09-22 15:30:25.433  1656  1705 I TrickyStore: hack key for u10205 KeyAttestation
09-22 15:30:25.446  1656  1705 I TrickyStore: return hacked cert of uid=10205 a=KeyAttestation
09-22 15:31:26.439  1656  1705 I TrickyStore: remove key for u10205 KeyAttestation because service.deleteKey
09-22 15:31:26.493  1656  1705 I TrickyStore: hack key for u10205 KeyAttestation
09-22 15:31:26.496  1656  1705 I TrickyStore: return hacked cert of uid=10205 a=KeyAttestation
09-22 15:31:30.443  1656  1705 I TrickyStore: key u10141 unstable.c7202ece89390c490b1b94d5b71225e1.fallback not in our keystore, try re-gen!
09-22 15:31:30.484  1656  1705 I TrickyStore: hack key for u10141 unstable.c7202ece89390c490b1b94d5b71225e1.-6114047154903938737
09-22 15:31:30.489  1656  1705 I TrickyStore: return hacked cert of uid=10141 a=unstable.c7202ece89390c490b1b94d5b71225e1.-6114047154903938737
09-22 15:31:30.496  1656  1705 I TrickyStore: remove key for u10141 unstable.c7202ece89390c490b1b94d5b71225e1.-6114047154903938737 because service.deleteKey
09-22 15:31:33.862  1656  1705 I TrickyStore: key u10141 unstable.c7202ece89390c490b1b94d5b71225e1.fallback not in our keystore, try re-gen!
09-22 15:31:33.929  1656  1705 I TrickyStore: hack key for u10141 unstable.c7202ece89390c490b1b94d5b71225e1.1886425526805407105
09-22 15:31:33.933  1656  1705 I TrickyStore: return hacked cert of uid=10141 a=unstable.c7202ece89390c490b1b94d5b71225e1.1886425526805407105
09-22 15:31:33.942  1656  1705 I TrickyStore: remove key for u10141 unstable.c7202ece89390c490b1b94d5b71225e1.1886425526805407105 because service.deleteKey
```
![1-Screenshot_20240922-153253_Key Attestation](https://github.com/user-attachments/assets/20c1a522-68b4-4238-bace-bf3a73f3c9b5)

release-2:
```
09-22 15:34:39.512  1655  1697 I TrickyStore: key u10141 unstable.c7202ece89390c490b1b94d5b71225e1.fallback not in our keystore, try re-gen!
09-22 15:34:39.578  1655  1697 I TrickyStore: hack key for u10141 unstable.c7202ece89390c490b1b94d5b71225e1.-2577558562746111851
09-22 15:34:39.630  1655  1697 I TrickyStore: return hacked cert of uid=10141 a=unstable.c7202ece89390c490b1b94d5b71225e1.-2577558562746111851
09-22 15:34:39.637  1655  1697 I TrickyStore: remove key for u10141 unstable.c7202ece89390c490b1b94d5b71225e1.-2577558562746111851 because service.deleteKey
09-22 15:34:40.811  1655  1697 I TrickyStore: hack key for u10205 KeyAttestation
09-22 15:34:40.851  1655  1697 I TrickyStore: return hacked cert of uid=10205 a=KeyAttestation
09-22 15:35:07.089  1655  1697 I TrickyStore: key u10141 unstable.c7202ece89390c490b1b94d5b71225e1.fallback not in our keystore, try re-gen!
09-22 15:35:07.132  1655  1697 I TrickyStore: hack key for u10141 unstable.c7202ece89390c490b1b94d5b71225e1.-6804707861116192707
09-22 15:35:07.136  1655  1697 I TrickyStore: return hacked cert of uid=10141 a=unstable.c7202ece89390c490b1b94d5b71225e1.-6804707861116192707
09-22 15:35:07.144  1655  1697 I TrickyStore: remove key for u10141 unstable.c7202ece89390c490b1b94d5b71225e1.-6804707861116192707 because service.deleteKey
09-22 15:35:11.261  1655  4908 I TrickyStore: key u10141 unstable.c7202ece89390c490b1b94d5b71225e1.fallback not in our keystore, try re-gen!
09-22 15:35:11.309  1655  4908 I TrickyStore: hack key for u10141 unstable.c7202ece89390c490b1b94d5b71225e1.-6083841220591509687
09-22 15:35:11.317  1655  4908 I TrickyStore: return hacked cert of uid=10141 a=unstable.c7202ece89390c490b1b94d5b71225e1.-6083841220591509687
09-22 15:35:11.331  1655  4908 I TrickyStore: remove key for u10141 unstable.c7202ece89390c490b1b94d5b71225e1.-6083841220591509687 because service.deleteKey
09-22 15:35:30.303  1655  1697 I TrickyStore: remove key for u10205 KeyAttestation because service.deleteKey
09-22 15:35:30.363  1655  1697 I TrickyStore: hack key for u10205 KeyAttestation
09-22 15:35:30.369  1655  1697 I TrickyStore: return hacked cert of uid=10205 a=KeyAttestation
09-22 15:35:35.823  1655  1697 I TrickyStore: key u10141 unstable.c7202ece89390c490b1b94d5b71225e1.fallback not in our keystore, try re-gen!
09-22 15:35:35.876  1655  1697 I TrickyStore: hack key for u10141 unstable.c7202ece89390c490b1b94d5b71225e1.8266651775190191729
09-22 15:35:35.884  1655  1697 I TrickyStore: return hacked cert of uid=10141 a=unstable.c7202ece89390c490b1b94d5b71225e1.8266651775190191729
09-22 15:35:35.907  1655  1697 I TrickyStore: remove key for u10141 unstable.c7202ece89390c490b1b94d5b71225e1.8266651775190191729 because service.deleteKey
09-22 15:35:38.459  1655  1697 I TrickyStore: key u10141 unstable.c7202ece89390c490b1b94d5b71225e1.fallback not in our keystore, try re-gen!
09-22 15:35:38.510  1655  1697 I TrickyStore: hack key for u10141 unstable.c7202ece89390c490b1b94d5b71225e1.-4977557468127591350
09-22 15:35:38.514  1655  1697 I TrickyStore: return hacked cert of uid=10141 a=unstable.c7202ece89390c490b1b94d5b71225e1.-4977557468127591350
09-22 15:35:38.541  1655  1697 I TrickyStore: remove key for u10141 unstable.c7202ece89390c490b1b94d5b71225e1.-4977557468127591350 because service.deleteKey
```
![2-Screenshot_20240922-153615_Key Attestation](https://github.com/user-attachments/assets/24ec69a3-1668-4ea6-9db3-3726d9547108)

Both work but -2 looks more complete with the non-zero verifiedBootHash, so I think we have a winner! 🎉👏

**Comment by osm0sis** [comment]
release-2 working great on all my other devices as well, e.g. OnePlus 9 Pro (teeBroken=true faked KeyMint 1.0) and Poco X2 (teeBroken=false Keymaster 4.0). 😁

**Comment by osm0sis** [comment]
@aviraxp @5ec1cff I notice the 1.2.0-RC2 build has the zeroed verifiedBootHash like release-1 above. Was this preferable to the populated verifiedBootHash release-2 had for some reason?

**Comment by aviraxp** [comment]
> @aviraxp @5ec1cff I notice the 1.2.0-RC2 build has the zeroed verifiedBootHash like release-1 above. Was this preferable to the populated verifiedBootHash release-2 had for some reason?

Hash of value 0 is pretty normal on old devices. I would like to hack as little as possible.

**Comment by osm0sis** [comment]
Makes sense. Thanks!

**Comment by kartikbillimoria** [comment]
> [Tricky-Store-v1.2.0-RC1-148-1d482fa-release-1.zip](https://github.com/user-attachments/files/17089566/Tricky-Store-v1.2.0-RC1-148-1d482fa-release-1.zip) [Tricky-Store-v1.2.0-RC1-148-1d482fa-release-2.zip](https://github.com/user-attachments/files/17089567/Tricky-Store-v1.2.0-RC1-148-1d482fa-release-2.zip) try these 2

Unable to install via apatch, getting error, failed to prepare environment

**Comment by pndwal** [comment]
> Unable to install via apatch, getting error, failed to prepare environment

Try beta release, Tricky-Store-v1.2.0-RC2-149-323b944-release with release-1 test (above) merged?... Reported working with APatch...

**Comment by kartikbillimoria** [comment]
I can confirm it is working fine, managed to install Tricky-Store-v1.2.0-RC2-149-323b944-release.

Thanks
