### ISSUE TITLE
TrickyStore Module Version 1.1.3 Auto Disabled And Cloud Not Enabled After Modules.img Shrink in KernelSU

### ISSUE THREAD

**Issue by BA7JCM** [5ec1cff/TrickyStore#61]
After flashing the TrickyStore module version 1.1.3 in KernelSU, the module works fine after reboot. Shamiko also functions correctly with the output "Shamiko is working with app profile" in the "Modules" section of the KernelSU manager.

However, after running the command `su -c /data/adb/ksud module shrink` to shrink the `modules.img` file to its actual size, and rebooting again, the TrickyStore module becomes disabled. Shamiko continues to work fine.

If I try to re-enable the TrickyStore module by toggling its switch on, and then reboot again, the module remains disabled, and Shamiko displays "unsupported environment."

I have tried this with multiple versions, including TrickyStore versions 1.1.0 through 1.1.3, and all exhibit the same issue. As long as I don't shrink `modules.img` after flashing, everything works as expected. The last version of TrickyStore that works normally after shrinking `modules.img` is version 1.0.3.

### Environment

- KernelSU Version: 11928 (both manager and ksud)
- KernelSU Mode: LKM Mode
- Kernel Version: GKI 5.15.78-Android13
- System: MIUI China ROM
- MIUI Version: 14.0.4.UMBCNXM
- Android Version: 14 (with October 1, 2023 security patch)
- Device: Xiaomi 13 Pro (China Version)

**Comment by aviraxp** [comment]
Should be fixed with 1.2.0.
