### ISSUE TITLE
Attestation broken for PCS

### ISSUE THREAD

**Issue by androidacy-user** [5ec1cff/TrickyStore#63]
On pixels, Private Compute Services requests an attestation for certain actions. With `!` forcing generation, PCS refuses to download anything, but with default mode the following exception is thrown

```
09-01 18:46:32.511 E/TrickyStore( 1404): Bb: cannot create signer: Signature initialized as EC (not EC)
```

With !: (not TrickyStore error but showing certificate generation doesn't work here)
```
09-01 18:59:33.140 E/ProtectedDownloadGrpcBindableService(18445): ekx: INTERNAL: Received unexpected EOS on empty DATA frame from server
```

**Comment by aviraxp** [comment]
Can you provide the apk?

**Comment by androidacy-user** [comment]
> Can you provide the apk?

https://file.io/8x35VodC0prV (single download link)

**Comment by aviraxp** [comment]
Need full log by trickystore

**Comment by androidacy-user** [comment]
> Need full log by trickystore

[log.txt](https://github.com/user-attachments/files/16858880/log.txt)

**Comment by aviraxp** [comment]
Please test on upcoming version and report back if issue still exists.
