### ISSUE TITLE
Google Authenticator doesn't work

### ISSUE THREAD

**Issue by MhmRdd** [5ec1cff/TrickyStore#64]
Google Authenticator doesn't work when package is added to target list of tricky store.

**Comment by pershoot** [comment]
@MhmRdd Why are you adding this application to target.txt?  It appears to function fine, without any (special) intervention.

**Comment by aviraxp** [comment]
It works here on 1.1.3..

**Comment by MhmRdd** [comment]
> @MhmRdd Why are you adding this application to target.txt?  It appears to function fine, without any (special) intervention.

In a recent update they created a bash script to list all packages and put them in target.txt, so it affected my google authenticator, i had to manually remove it, but i don't see any sense of how TrickyStore could interrupt some other apps'authentication features.
