### ISSUE TITLE
After TS post-update reboot TS disables itself

### ISSUE THREAD

**Issue by osm0sis** [5ec1cff/TrickyStore#65]
"Failed to prepare environment" is confirmed fixed with 1.1.3 (updated from 1.1.2), but after the reboot TS disabled itself again. Magisk 27007.

_Originally posted by @osm0sis in https://github.com/5ec1cff/TrickyStore/issues/57#issuecomment-2308936116_

Still an issue updating from 1.1.3 to 1.2.0-RC1.

**Comment by aviraxp** [comment]
Disable is caused by 1.1.3, not 1.2.0. 1.2.0 should fix it on next installs.

**Comment by osm0sis** [comment]
Perfect! Thanks!
