### ISSUE TITLE
Regression resulting in losing Strong after 1.1.2 with a working configuration.

### ISSUE THREAD

**Issue by badabing2005** [5ec1cff/TrickyStore#66]
One Plus 5 with Lineage OS (Android 14)
    
    Magisk Version:                  8e82113b:27007
    Magisk Denylist enforced:        False
    Magisk Zygisk enabled:           True
    Magisk Modules:
        Systemless Hosts                    enabled   1.0
        Play Integrity Fork                 enabled   v10
        Tricky Store                        enabled   v1.1.2 (123-94176b9-release)

With a well known beta print used in PiFork and a valid keybox, the device passes strong.
If I add `!` to the targets.txt
```
com.google.android.gms!
io.github.vvb2060.keyattestation!
io.github.vvb2060.mahoshojo!
icu.nullptr.nativetest!
```

If I remove the `!` and the PI test passes only Device integrity.

If I Install TS 1.1.3 or 1.2 RC
With or without `!` in the targets, I can never achieve strong.

I downgrade to 1.1.2 and it passes strong again.

**Comment by aviraxp** [comment]
1.1.2 and 1.1.3 is same as for key attestation spoofing (it even doesn't touch any code related to it).

**Comment by osm0sis** [comment]
@badabing2005 any improvement with RC2?

**Comment by badabing2005** [comment]
> @badabing2005 any improvement with RC2?

Where is the RC2?
The last build in Github actions is more than a month old.
I don't use Telegram.

**Comment by osm0sis** [comment]
GitHub Releases, as of yesterday.

https://github.com/5ec1cff/TrickyStore/releases

**Comment by badabing2005** [comment]
API Quota reached on the testing apps, 
no PS account on the test device.
I guess we'll know more tomorrow.

**Comment by badabing2005** [comment]
@osm0sis 
RC2 is good.
