### ISSUE TITLE
HW attestation no longer passing for non broken TEE

### ISSUE THREAD

**Issue by SpeedyCraftah** [5ec1cff/TrickyStore#71]
Not really an issue since this was expected, but I'm opening this for documentation.

Just recently, hardware attestation stopped passing for me and my friend without a hardware keybox on a device with a non-broken TEE on TrickyStore 1.1.3 with Play Integrity Fix.

Basic and Device integrity still passes without an issue though.

I presume Google fixed this now? Is the only option to find a non-revoked hardware keybox now?

I do wonder how this module could initially pass hardware attestation without a custom hardware keybox though, this could only mean this module somehow tricked the TEE firmware into incorrectly signing a custom certificate / positive attestation verdict since you can't really get around the cryptography associated with hardware attestation, so it only leaves us with either extracting leaked hardware keys from the TEE, or getting the TEE to somehow sign a positive verdict anyways. That's what I find most interesting but can't find much information about.

**Comment by aviraxp** [comment]
This module cannot pass hardware attestation without keybox. Likely Play integrity fix replace your keybox with a unrevoked one.

**Comment by SpeedyCraftah** [comment]
> This module cannot pass hardware attestation without keybox. Likely Play integrity fix replace your keybox with a unrevoked one.

I thought chiteroman only provided keyboxes that pass DEVICE and BASIC only, not hardware?

**Comment by aviraxp** [comment]
You are wrong.

**Comment by Magniquick** [comment]
Pssst: this may help https://github.com/osm0sis/PlayIntegrityFork?tab=readme-ov-file#about-spoofing-advanced-settings
