### ISSUE TITLE
重启以后替换的keybox会重置为默认内置的？

### ISSUE THREAD

**Issue by MIkeeJY** [5ec1cff/TrickyStore#74]
重启以后替换的keybox会重置为默认内置的？Tricky-Store-v1.2.0-RC2-149-323b944-release     pixel6 Android 13

**Comment by MIkeeJY** [comment]
手动替换后 重启了又被替换成默认的内置了？

**Comment by MIkeeJY** [comment]
@aviraxp apatch(10933) + pixel6 android 13有此问题，别的手机正常
oriole:/data/adb/tricky_store # chmod 600 keybox.xml     给了600权限，重启依旧被替换~

**Comment by aviraxp** [comment]
自查别的模块

**Comment by MIkeeJY** [comment]
> 自查别的模块

多谢 查到了是PlayIntegrityFix_v17.5 导致的 更新到 17.7一切正常
