### ISSUE TITLE
NO_INTEGRITY

### ISSUE THREAD

**Issue by advokat11** [5ec1cff/TrickyStore#81]
NO_INTEGRITY after trickystore install. Even after deletion.
![Screenshot_2024-10-30-20-36-09-27_710528209a6e8323786b539cad831607.jpg](https://github.com/user-attachments/assets/0f2fa3ee-74c3-4738-bd12-9b5ce383ddf4)

**Comment by VisionR1** [comment]
> NO_INTEGRITY after trickystore install. Even after deletion. ![Screenshot_2024-10-30-20-36-09-27_710528209a6e8323786b539cad831607.jpg](https://private-user-images.githubusercontent.com/59486045/381669166-0f2fa3ee-74c3-4738-bd12-9b5ce383ddf4.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAzMTM4OTUsIm5iZiI6MTczMDMxMzU5NSwicGF0aCI6Ii81OTQ4NjA0NS8zODE2NjkxNjYtMGYyZmEzZWUtNzRjMy00NzM4LWJkMTItOWI1Y2UzODNkZGY0LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDMwVDE4Mzk1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgyZGU3OGViZGZlNWYzNzdjN2UwM2I0NzM2ZjZiZTU1MGNmMTNhNGYyOWEwNjQ4ZTIzMjU0MGUzZWZiNjYzYmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.xIV4ErnNh7lQjXndBUlRddNeBcZLC7SDmWVy229Rzho)

Little info.
Custom Rom?

**Comment by advokat11** [comment]
> > NO_INTEGRITY after trickystore install. Even after deletion. ![Screenshot_2024-10-30-20-36-09-27_710528209a6e8323786b539cad831607.jpg](https://private-user-images.githubusercontent.com/59486045/381669166-0f2fa3ee-74c3-4738-bd12-9b5ce383ddf4.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAzMTM4OTUsIm5iZiI6MTczMDMxMzU5NSwicGF0aCI6Ii81OTQ4NjA0NS8zODE2NjkxNjYtMGYyZmEzZWUtNzRjMy00NzM4LWJkMTItOWI1Y2UzODNkZGY0LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDMwVDE4Mzk1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgyZGU3OGViZGZlNWYzNzdjN2UwM2I0NzM2ZjZiZTU1MGNmMTNhNGYyOWEwNjQ4ZTIzMjU0MGUzZWZiNjYzYmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.xIV4ErnNh7lQjXndBUlRddNeBcZLC7SDmWVy229Rzho)
> 
> Little info. Custom Rom?

stock oneplus 12 oxygen os 850

**Comment by advokat11** [comment]
![Screenshot_2024-10-30-21-53-11-72_baaa51257c82a8b3f281ce09e6f2493f.jpg](https://github.com/user-attachments/assets/fa806704-12a1-49f7-9153-44113e8ff1ea)

![Screenshot_2024-10-30-21-52-47-51_6029a840d9ecf62a76e79d1fe4d50b0c.jpg](https://github.com/user-attachments/assets/7c9b13bd-16af-4b6a-9922-6d13cbff67c2)

![Screenshot_2024-10-30-21-53-25-15_710528209a6e8323786b539cad831607.jpg](https://github.com/user-attachments/assets/ec1ffd0a-21e8-4a5f-9cd1-a1087af4864b)

![Screenshot_2024-10-30-21-53-32-80_084ab3bc34f7aa7ccff83653f52abafc.jpg](https://github.com/user-attachments/assets/47bd51aa-4bb9-4a6e-9d3b-7cf757c79bc2)

![Screenshot_2024-10-30-21-53-36-76_084ab3bc34f7aa7ccff83653f52abafc.jpg](https://github.com/user-attachments/assets/2f4c088b-b28b-4897-998e-35a6f94be582)

![Screenshot_2024-10-30-21-53-15-38_baaa51257c82a8b3f281ce09e6f2493f.jpg](https://github.com/user-attachments/assets/6300f87c-fcc0-421d-9233-904c352085c5)

**Comment by VisionR1** [comment]
For test, you can disable all modules, except the PIF and tricky store?
And before install tricky store, what say inside in the key attestation?
