### ISSUE TITLE
Unable to pass even basic integrity

### ISSUE THREAD

**Issue by ks716** [5ec1cff/TrickyStore#9]
Im on one plus 7, using v1.0.1 
key attestation is working in key attestation demo
Play integrity test is not passing even basic
I am on latest release of TrickyStore

**Comment by VisionR1** [comment]
> Im on one plus 7, using v1.0.1 key attestation is working in key attestation demo Play integrity test is not passing even basic I am on latest release of TrickyStore

You mean in Key attestation show you BL is locked?
Do you have a valid keybox.xml?

**Comment by ks716** [comment]
Yes

**Comment by VisionR1** [comment]
> Yes

Unfortunately If is StrongBox, can't work

**Comment by VisionR1** [comment]
Something else I want to ask.
After you install this module and reboot, the tricky_store folder inside in the /data/adb/ create automatically for you?

**Comment by busybox11** [comment]
It should create it automatically yes.

**Comment by VisionR1** [comment]
> It should create it automatically yes.

In you create automatically?
Because we have this issue there
https://github.com/5ec1cff/TrickyStore/issues/7

**Comment by busybox11** [comment]
Have you tested it?

**Comment by VisionR1** [comment]
> Have you tested it?

Sure, for that I ask you.
Now go to try latest.
